### ISSUE TITLE
requied fields in adding users form

### ISSUE THREAD

**Issue by dmytrobohdanov** [shpp/mafia-portal#17]
- they should be marked with '*'
- email, phone are not requied

**Comment by skhablyuk** [comment]
phone need for login

**Comment by dmytrobohdanov** [comment]
but not all users need to have access to closed part of portal 
so can we make phone field reqiued only for some specified categories of users?

**Comment by dmytrobohdanov** [comment]
or perhaps just leave phone field as reqiued, but not email

**Comment by skhablyuk** [comment]
ok
